#!/bin/bash
if [ -e launcher.opt ] ; then
 . launcher.opt
 fi

 if [ -e  ] ; then
 ./Release/distance-checker -l distance-output.txt -g   ${OPTION} $@
 else
 ./Release/distance-checker -l distance-output.txt $@ -G 
 fi
