#!/bin/bash

DIR=$1
REPOS_TOP=..

if [ ! -d ${DIR} ] ; then 
	echo "Error: missing dirctory path operand"
	echo "Usage: ./put-conf <dir>"
	exit 1
fi

# visualizer
CONF=${DIR}/Visualizer.conf
PUTDIR=${REPOS_TOP}/visualizer/
if [ -f ${CONF} ]	; then
	echo "apply ${CONF} to ${PUTDIR}"
	cp ${CONF} ${PUTDIR}
else
	echo "missing visualizer conf"	
fi

# psm-position-tracker
CONF=${DIR}/psm-pos-tracker.conf
PUTDIR=${REPOS_TOP}/psm-position-tracker/
if [ -f ${CONF} ]	; then
	echo "apply ${CONF} to ${PUTDIR}"
	cp ${CONF} ${PUTDIR}
else
	echo "missing psm position tracker conf"	
fi


# multilogger
CONF=${DIR}/logging.list
PUTDIR=${REPOS_TOP}/multilogger/
if [ -f ${CONF} ]	; then
	echo "apply ${CONF} to ${PUTDIR}"
	cp ${CONF} ${PUTDIR}
else
	echo "missing logging list"	
fi


# urg-proxy
CONF=${DIR}/urg-dev.conf
PUTDIR=${REPOS_TOP}/urg-proxy/
if [ -f ${CONF} ]	; then
	echo "apply ${CONF} to ${PUTDIR}"
	cp ${CONF} ${PUTDIR}
else
	echo "missing urg device conf"	
fi


# ls-coordinate-converter
CONF=${DIR}/front-ls-coordinate-converter.conf
PUTDIR=${REPOS_TOP}/ls-coordinate-converter/
if [ -f ${CONF} ]	; then
	echo "apply ${CONF} to ${PUTDIR}"
	cp ${CONF} ${PUTDIR}
else
	echo "missing front laser scanner coordinate converter conf"	
fi

CONF=${DIR}/upward-ls-coordinate-converter.conf
PUTDIR=${REPOS_TOP}/ls-coordinate-converter/
if [ -f ${CONF} ]	; then
	echo "apply ${CONF} to ${PUTDIR}"
	cp ${CONF} ${PUTDIR}
else
	echo "missing upward laser scanner coordinate converter conf"	
fi

CONF=${DIR}/vertical-ls-coordinate-converter.conf
PUTDIR=${REPOS_TOP}/ls-coordinate-converter/
if [ -f ${CONF} ]	; then
	echo "apply ${CONF} to ${PUTDIR}"
	cp ${CONF} ${PUTDIR}
else
	echo "missing vertical laser scanner coordinate converter conf"	
fi



# particle-localizer
CONF=${DIR}/particle-localizer.conf
PUTDIR=${REPOS_TOP}/particle-localizer/
if [ -f ${CONF} ]	; then
	echo "apply ${CONF} to ${PUTDIR}"
	cp ${CONF} ${PUTDIR}
else
	echo "missing particle localizer conf"	
fi


# psm-particle-evaluator
CONF=${DIR}/psm-particle-evaluator.conf
PUTDIR=${REPOS_TOP}/psm-particle-evaluator/
if [ -f ${CONF} ]	; then
	echo "apply ${CONF} to ${PUTDIR}"
	cp ${CONF} ${PUTDIR}
else
	echo "missing psm particle evaluator conf"	
fi


# ysd-path-planner
CONF=${DIR}/ysd-path-planner.conf
PUTDIR=${REPOS_TOP}/ysd-path-planner/
if [ -f ${CONF} ]	; then
	echo "apply ${CONF} to ${PUTDIR}"
	cp ${CONF} ${PUTDIR}
else
	echo "missing ysd path planner conf"	
fi



