#############################################################################
# Makefile for building: route-editor
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Oct 13 23:21:23 2013
# Project:  ../src/route-editor.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../src/route-editor.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I../src -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I../../tkglib -I../../gndlib -I../../visualizer/src -I/usr/X11R6/include -I. -I../src -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib -lGLU -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../src/main.cpp \
		../src/window.cpp \
		../src/widget-msg.cpp \
		../src/widget-gl.cpp \
		../../visualizer/src/menu-handler.cpp \
		../../visualizer/src/map-viewer.cpp \
		../src/route-edit.cpp moc_window.cpp \
		moc_widget-msg.cpp \
		moc_widget-gl.cpp \
		moc_menu-handler.cpp \
		moc_map-viewer.cpp
OBJECTS       = main.o \
		window.o \
		widget-msg.o \
		widget-gl.o \
		menu-handler.o \
		map-viewer.o \
		route-edit.o \
		moc_window.o \
		moc_widget-msg.o \
		moc_widget-gl.o \
		moc_menu-handler.o \
		moc_map-viewer.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		../src/route-editor.pro
QMAKE_TARGET  = route-editor
DESTDIR       = 
TARGET        = route-editor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../src/route-editor.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../src/route-editor.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../src/route-editor.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/route-editor1.0.0 || $(MKDIR) .tmp/route-editor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/route-editor1.0.0/ && $(COPY_FILE) --parents ../src/window.hpp ../../tkglib/tkg-utility.hpp ../../tkglib/tkg-opengl.hpp ../../tkglib/tkg-geometry.hpp ../../tkglib/tkg-debug.hpp ../../tkglib/tkg-config.hpp ../src/widget-msg.hpp ../src/widget-gl.hpp ../../visualizer/src/menu-handler.hpp ../../visualizer/src/map-viewer.hpp ../src/route-edit.hpp .tmp/route-editor1.0.0/ && $(COPY_FILE) --parents ../src/main.cpp ../src/window.cpp ../src/widget-msg.cpp ../src/widget-gl.cpp ../../visualizer/src/menu-handler.cpp ../../visualizer/src/map-viewer.cpp ../src/route-edit.cpp .tmp/route-editor1.0.0/ && (cd `dirname .tmp/route-editor1.0.0` && $(TAR) route-editor1.0.0.tar route-editor1.0.0 && $(COMPRESS) route-editor1.0.0.tar) && $(MOVE) `dirname .tmp/route-editor1.0.0`/route-editor1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/route-editor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_window.cpp moc_widget-msg.cpp moc_widget-gl.cpp moc_menu-handler.cpp moc_map-viewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_window.cpp moc_widget-msg.cpp moc_widget-gl.cpp moc_menu-handler.cpp moc_map-viewer.cpp
moc_window.cpp: ../src/window.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../src/window.hpp -o moc_window.cpp

moc_widget-msg.cpp: ../src/widget-msg.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../src/widget-msg.hpp -o moc_widget-msg.cpp

moc_widget-gl.cpp: ../src/widget-gl.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../src/widget-gl.hpp -o moc_widget-gl.cpp

moc_menu-handler.cpp: ../../visualizer/src/menu-handler.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../../visualizer/src/menu-handler.hpp -o moc_menu-handler.cpp

moc_map-viewer.cpp: ../../visualizer/src/map-viewer.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../../visualizer/src/map-viewer.hpp -o moc_map-viewer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: ../src/main.cpp ../src/window.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../src/main.cpp

window.o: ../src/window.cpp ../src/window.hpp \
		../src/widget-gl.hpp \
		../src/widget-msg.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o ../src/window.cpp

widget-msg.o: ../src/widget-msg.cpp ../src/widget-msg.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget-msg.o ../src/widget-msg.cpp

widget-gl.o: ../src/widget-gl.cpp ../src/window.hpp \
		../src/widget-gl.hpp \
		../src/widget-msg.hpp \
		../src/route-edit.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget-gl.o ../src/widget-gl.cpp

menu-handler.o: ../../visualizer/src/menu-handler.cpp ../../visualizer/src/menu-handler.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menu-handler.o ../../visualizer/src/menu-handler.cpp

map-viewer.o: ../../visualizer/src/map-viewer.cpp ../../visualizer/src/map-viewer.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o map-viewer.o ../../visualizer/src/map-viewer.cpp

route-edit.o: ../src/route-edit.cpp ../src/route-edit.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o route-edit.o ../src/route-edit.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

moc_widget-msg.o: moc_widget-msg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget-msg.o moc_widget-msg.cpp

moc_widget-gl.o: moc_widget-gl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget-gl.o moc_widget-gl.cpp

moc_menu-handler.o: moc_menu-handler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_menu-handler.o moc_menu-handler.cpp

moc_map-viewer.o: moc_map-viewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_map-viewer.o moc_map-viewer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

